In [2]:
import pandas as pd
import numpy as np
from collections import Counter

In [3]:
class Node:
    def __init__(self, value=None, threshold=None, left=None, right=None):
        self.feature = value
        self.left = left
        self.right = right

    def is_leaf(self):
        return self.right is None and self.left is None

In [5]:
ds = pd.read_csv('data.csv')

X = ds.iloc[:, 0:5].values
y = ds['name'].values

# print(X)
# print(y)

clf = DecisionTree()
clf.fit(X, y)

y_pred = clf.predict(X)

# print(y)
# print(y_pred)

clf.print_tree(clf.root)

X_left [[-1 -1  1 -1]
 [ 1  1  1  1]
 [-1 -1  1 -1]
 [-1  1  1  1]
 [ 1 -1 -1  1]
 [-1  1  1 -1]
 [ 1 -1 -1 -1]]
y_left ['Alice' 'David' 'Eve' 'Grace' 'Henry' 'Iris' 'Jack']
X_right [[ 1  1  1  1]
 [ 1  1 -1 -1]
 [ 1 -1 -1  1]]
y_right ['Bob' 'Charlie' 'Frank']
X_left [[-1  1 -1]
 [-1  1 -1]
 [ 1  1  1]
 [ 1  1 -1]]
y_left ['Alice' 'Eve' 'Grace' 'Iris']
X_right [[ 1  1  1]
 [-1 -1  1]
 [-1 -1 -1]]
y_right ['David' 'Henry' 'Jack']
left_subtree None
right_subtree None
X_left [[ 1  1 -1]
 [ 1 -1  1]]
y_left ['Charlie' 'Frank']
X_right [[1 1 1]]
y_right ['Bob']
left_subtree None
right_subtree None
left_subtree <__main__.Node object at 0x7f8f6a518c10>
right_subtree <__main__.Node object at 0x7f8f26ea0f10>
Left:
  Leaf Node: 2
Right:
depth: 0
